@startuml PoDobavlenieZanyatiq.wsd

actor "Методист" as pl

boundary "Домашнее окно\n методиста" as bo
boundary "Вкладка\n Просмотр готовых занятий" as bo1
boundary "Окно настройки\n занятия" as bo2

control "Проверка данных" as co3

entity "База данных" as en

boundary "Окно ошибки" as err #Red


pl -> bo : Нажата вкладка\n Просмотр готовых занятий 

bo -> bo1 : Отображение вкладки\n Просмотр готовых занятий

pl -> bo1 : Нажата кнопка Добавление

bo1 -> bo2 : Отображение окна\n настройки занятия

pl -> bo2 : Введены данные и нажата кнопка Готово

bo2 -> co3

co3 -> en : Запрос

en --> co3 : Ответ

co3 -> co3 : Проверка ответа

alt Данные корректны

co3 -> en : Запись данных

co3 -> bo1

else Данные не корректны

co3 -> err : Вызов окна ошибки

err --> pl

end

@enduml