@startuml PoDobavleniePolzovatelya.wsd

actor "Администратор" as pl

boundary "Домашнее окно\n администратора" as bo

boundary "Вкладка\n Добавить пользователя" as bo1

control "Проверка данных" as co2

entity "База данных" as en

boundary "Окно ошибки" as err #Red

pl -> bo : Нажата вкладка\n Добавить пользователя

bo -> bo1 : Отображение вкладки\n Добавить пользователя


pl -> bo1 : Выбрана роль

bo1 -> bo1 : Открытие новых полей

pl -> bo1 : Внесены данные и нажата кнопка Готово

bo1 -> co2

co2 -> en : Запрос

en --> co2 : Ответ

co2 -> co2 : Проверка ответа

alt Данные корректны

co2 -> en : Запись данных

else Данные не корректы

co2 -> err : Вызов окна ошибки

err --> pl

end

@enduml