@startuml PoProsmotrMoixZanyatiq.wsd

actor "Пользователя" as pl

boundary "Домашнее окно пользователя" as bo

control "Открытие вкладки\n Мои занятия" as co

boundary "Вкладка Мои занятия" as bo1

pl --> bo: Нажата вкладка Мои занятия

bo -> co

co -> bo1

@enduml