@startuml Listener.wsd

state "Окно входа в программу" as loginWindow
state "Домашнее окно" as homeWindow
state "Окно просмотра своих занятий" as cursWindow
state "Окно профиля пользователя" as profileWindow

loginWindow : Пользователь может:
loginWindow : -Ввести данные для входа
loginWindow : -Войти

homeWindow : Пользователь может:
homeWindow : -Открыть вкладку Мои занятия
homeWindow : -Открыть вкладку профиля пользователя
homeWindow : -Закрыть программу

cursWindow : Пользователь может:
cursWindow : -Просматривать иформацию\n о своих занятиях

profileWindow : Пользователь может:
profileWindow : -Просмотреть свои ФИО
profileWindow : -Просмотреть свою специальность
profileWindow : -Просмотреть свое отделение
profileWindow : -Просмотреть свою группу
profileWindow : -Выйти из системы


[*] --> loginWindow
loginWindow -> homeWindow : Нажата кнопка Войти
homeWindow -up-> cursWindow : Нажата вкладка\n Мои занятия
homeWindow -down-> profileWindow : Нажата вкладка\n профиль
homeWindow -right->[*] : Окно закрыто
profileWindow --> loginWindow : Нажата кнопка Выход 


@enduml