@startuml PrProsmotrMoixZanyatiq.wsd

actor "Пользователь" as pl

control "Открытие вкладки\n Мои занятия" as co

boundary "Домашнее окно пользователя" as bo
boundary "Вкладка Мои занятия" as bo1

pl --> bo
bo --> co : Нажата вкладка\n Мои занятия
co -left-> bo1

@enduml